Repository yutotnh/spirit, pull requests merged in 2022-11, with the labels that each got.

#2 fix: type in MdLed.h
  include/MdLed.h
Labels: documentation

#4 GitHub Actionsにclang-formatとビルドチェックを追加する
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/style-check.yml
Labels: enhancement

#7 update: テスト実行手順を変更
  README.md
Labels: documentation

#12 add: issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#13 add: pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#15 add: codeql.yml #14
  .github/workflows/codeql.yml
  .github/workflows/flawfinder.yml
Labels: enhancement

#16 update: fix feature issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#18 A3921対応
  CMakeLists.txt
  include/A3921.h
  include/interfaceDigitalOut.h
  include/interfaceMotor.h
  include/interfacePwmOut.h
  source/A3921.cpp
  tests/CMakeLists.txt
  tests/test_A3921.cpp
Labels: enhancement

#21 add: 開発に必要な拡張機能を.devcontainer.jsonに書いた #19
  .devcontainer/devcontainer.json
Labels: enhancement

#26 add: Doxygenデプロイ用のファイルを追加 #23
  .github/workflows/deploy-static.yml
  Doxyfile
Labels: enhancement

#29 update: 軽いリファクタリング #27
  include/A3921.h
  include/MdLed.h
  include/interfaceDigitalOut.h
  include/interfaceLeds.h
  include/interfaceMotor.h
  include/interfacePwmOut.h
  source/A3921.cpp
  source/MdLed.cpp
  tests/stubs.h
  tests/test_A3921.cpp
  tests/test_MdLed.cpp
Labels: enhancement

#30 update: install graphviz & doxygen #28
  .devcontainer/Dockerfile
Labels: enhancement

#31 fix: Initialize member variables of `stub.cpp`
  tests/stubs.h
Labels: bug

#32 Remove unused includes and variables
  include/interfaceMotor.h
  source/MdLed.cpp
Labels: bug

#33 Add: A3921のパルス周期に着目したテストを追加する
  source/A3921.cpp
  tests/stubs.h
  tests/test_A3921.cpp
Labels: bug

#36 update: Eliminate duty ratio range checks
  source/A3921.cpp
Labels: enhancement

#42 fix: リファクタリング等軽い変更を実施した
  include/A3921.h
  include/InterfaceDigitalOut.h
  include/InterfaceMotor.h
  include/InterfacePwmOut.h
  include/MdLed.h
  source/A3921.cpp
  source/MdLed.cpp
  tests/stubs.h
  tests/test_MdLed.cpp
Labels: enhancement

#43 changes:Slow DecayのPWMをlow sideに変更#37
  source/A3921.cpp
  tests/test_A3921.cpp
Labels: enhancement

#45 Add:Slow decay のPwm side を切り替える機能の追加。
  include/A3921.h
  source/A3921.cpp
  tests/test_A3921.cpp
Labels: enhancement

#47 fix: Change class from Mode to BlinkMode #46
  include/MdLed.h
  source/MdLed.cpp
  tests/test_MdLed.cpp
Labels: enhancement

#48 fix: いくつかの軽微な修正
  include/InterfaceMotor.h
  source/A3921.cpp
  tests/test_A3921.cpp
Labels: bug

#50 Dev Contaier 用の設定を充実させる #49
  .devcontainer/Dockerfile
  .gitignore
  .vscode/settings.json
  source/A3921.cpp
  tests/test_A3921.cpp
Labels: bug, enhancement

#52 update: A3921 の Reset 機能対応 #51
  include/A3921.h
  source/A3921.cpp
  tests/test_A3921.cpp
Labels: enhancement

#53 update: Encoding を UTF-8 にする設定を追加
  .vscode/settings.json
Labels: bug
