Repository yutotnh/spirit, pull requests merged in 2023-09, with the labels that each got.

#236 feat: 速度制御対応 #165
  .cspell.json
  CMakeLists.txt
  src/spirit.h
  src/spirit/include/InterfaceInterruptIn.h
  src/spirit/include/SpeedController.h
  src/spirit/platform/mbed/include/InterruptIn.h
  src/spirit/platform/mbed/source/InterruptIn.cpp
  src/spirit/src/SpeedController.cpp
  tests/CMakeLists.txt
  tests/stubs.h
  tests/test_SpeedController.cpp
Labels: enhancement

#278 feat: ゲインの初期値を暫定値から更新
  src/spirit/include/Motor.h
Labels: enhancement

#280 test: 正常系のテスト中にエラーが発生していないことを確認
  tests/test_A3921.cpp
  tests/test_Motor.cpp
  tests/test_SpeedController.cpp
Labels: enhancement

#274 docs: ドキュメント中の浮動小数点の接尾語を削除 #70
  src/spirit/include/A3921.h
  src/spirit/include/InterfacePwmOut.h
  src/spirit/include/Motor.h
Labels: documentation

#276 chore: GoogleTestのバージョンをv1.14.0に更新 #275
  tests/CMakeLists.txt
Labels: enhancement

#277 docs: ドキュメントの改善
  src/spirit/include/FakeUdpConverter.h
  src/spirit/include/MdLed.h
  src/spirit/include/Motor.h
  src/spirit/include/bfloat16.h
  src/spirit/include/mutex.h
  src/spirit/platform/arduino/include/PwmOut.h
Labels: documentation

#279 chore: add dependabot.yml
  .cspell.json
  .github/dependabot.yml
Labels: enhancement

#283 chore: 警告を増やし、警告発生時にエラーになるように変更
  .cspell.json
  CMakeLists.txt
  src/spirit/include/Id.h
  src/spirit/include/SpeedController.h
  src/spirit/src/Id.cpp
  src/spirit/src/PwmDataConverter.cpp
  src/spirit/src/SpeedController.cpp
  src/spirit/src/SpeedDataConverter.cpp
  src/spirit/src/bfloat16.cpp
  tests/CMakeLists.txt
  tests/integration_test.cpp
  tests/test_Id.cpp
  tests/test_Motor.cpp
  tests/test_SpeedController.cpp
  tests/test_adjust_duty_cycle.cpp
Labels: enhancement

#297 chore: depandabot の pull request のレビュワーを設定
  .github/dependabot.yml
Labels: enhancement

#298 fix: reviewers のエラーを修正
  .github/dependabot.yml
Labels: bug
