Repository yutotnh/spirit, pull requests merged in 2023-08, with the labels that each got.

#260 chore: ビルドディレクトリへの移動するコマンドを変更 #259
  .github/workflows/build.yml
Labels: enhancement

#261 chore: add Actionlint workflow
  .github/workflows/actionlint.yml
Labels: enhancement

#262 style: 仮数部のけち表現まわりの処理をわかりやすいように修正
  src/spirit/src/bfloat16.cpp
Labels: enhancement

#263 docs: CONTRIBUTING.mdを改善
  CONTRIBUTING.md
Labels: documentation

#264 chore: compile_commands.json を生成する
  CMakeLists.txt
Labels: enhancement

#265 chore: settings.json を改善
  .vscode/settings.json
Labels: enhancement

#266 feat: バージョン情報を追加 #157 #188
  src/spirit.h
  src/spirit/include/version.h
  src/spirit/src/Error.cpp
Labels: enhancement

#268 fix: メンバ関数のconst修飾を適切な形に修正
  src/spirit/include/A3921.h
  src/spirit/include/PwmDataConverter.h
  src/spirit/include/SpeedDataConverter.h
  src/spirit/platform/arduino/include/PwmOut.h
  src/spirit/src/A3921.cpp
  src/spirit/src/PwmDataConverter.cpp
  src/spirit/src/SpeedDataConverter.cpp
Labels: bug

#271 feat: CMakePresets.json 対応
  .vscode/settings.json
  CMakeLists.txt
  CMakePresets.json
  README.md
Labels: enhancement

#273 feat: adjust_duty_cycle() の state の範囲チェックを追加 #186
  src/spirit/include/adjust_duty_cycle.h
  tests/test_adjust_duty_cycle.cpp
Labels: enhancement
